version: "3.8"
services:
  my-scheduler:
    image: registry.k8s.io/kube-scheduler:v1.33.0
    network_mode: "host"
    volumes:
      - ./my-scheduler.yaml:/etc/kube-scheduler/my-scheduler.yaml
      - ./kubeconfig.yaml:/etc/kube-scheduler/kubeconfig.yaml
      - ./admin.crt:/etc/kube-scheduler/admin.crt
      - ./admin.key:/etc/kube-scheduler/admin.key
      - ./ca.crt:/etc/kube-scheduler/ca.crt
    command:
      - kube-scheduler
      - --config=/etc/kube-scheduler/my-scheduler.yaml
      - --secure-port=10260
      - --v=3
