apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://172.31.189.148:8080
  name: fake-api-server
contexts:
- context:
    cluster: fake-api-server
    user: fake-user
  name: fake-api-server
current-context: fake-api-server
kind: Config
preferences: {}
users:
- name: fake-user
  user: {}

