apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kube-scheduler/ca.crt
    server: https://127.0.0.1:32766
  name: kwok-kwok
contexts:
- context:
    cluster: kwok-kwok
    user: kwok-kwok
  name: kwok-kwok
current-context: kwok-kwok
kind: Config
preferences: {}
users:
- name: kwok-kwok
  user:
    client-certificate: /etc/kube-scheduler/admin.crt
    client-key: /etc/kube-scheduler/admin.key

